// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  bbox:            number[];
  center:          number[];
  context:         Context[];
  geometry:        Geometry;
  id:              string;
  language_es?:    Language;
  language?:       Language;
  place_name_es:   string;
  place_name:      string;
  place_type_name: string[];
  place_type:      string[];
  properties:      Properties;
  relevance:       number;
  text_es:         string;
  text:            string;
  type:            string;
}

export interface Context {
  ref:               string;
  country_code:      Language;
  id:                string;
  text:              string;
  text_es:           string;
  kind?:             Kind;
  "osm:place_type"?: string;
  language?:         Language;
  wikidata?:         string;
  language_es?:      Language;
}

export enum Language {
  Br = "br",
  Es = "es",
  MX = "mx",
}

export enum Kind {
  AdminArea = "admin_area",
  Place = "place",
}

export interface Geometry {
  type:        string;
  coordinates: number[];
}

export interface Properties {
  ref:               string;
  country_code:      Language;
  kind:              string;
  place_type_name:   string[];
  "osm:place_type"?: string;
}
